/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE DATABASE IF NOT EXISTS customer;

USE customer;

DROP TABLE IF EXISTS customer.cname;

CREATE TABLE  customer.cname (
id int(11) NOT NULL AUTO_INCREMENT,
firstName char(20) NOT NULL,
lastName char(20) NOT NULL,
PRIMARY KEY (id)
) ENGINE=MyISAM AUTO_INCREMENT=87 DEFAULT CHARSET=utf8;

/*!40000 ALTER TABLE cname DISABLE KEYS */;

LOCK TABLES cname WRITE;

INSERT INTO customer.cname VALUES
(37,'Sam','Johnson'),
(38,'Sarah','Simpson');
UNLOCK TABLES;

/*!40000 ALTER TABLE phone_number ENABLE KEYS */;

DROP TABLE IF EXISTS customer.phone_number;

CREATE TABLE  customer.phone_number (
id int(11) NOT NULL AUTO_INCREMENT,
phone varchar(20) NOT NULL,
PRIMARY KEY (id)
) ENGINE=MyISAM AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

/*!40000 ALTER TABLE phone_number DISABLE KEYS */;

LOCK TABLES phone_number WRITE;

INSERT INTO customer.phone_number VALUES
(1,'(208)345-6789'),
(2,'(208)321-4567'),

UNLOCK TABLES;

/*!40000 ALTER TABLE phone_number ENABLE KEYS */;

DROP TABLE IF EXISTS customer.address;

CREATE TABLE  customer.address (
customer_id int(11) NOT NULL,
street_address varchar(20) NOT NULL,
city varchar(20) NOT NULL,
state varchar(20) NOT NULL,
zipcode varchar(5) NOT NULL,
id int(11) NOT NULL AUTO_INCREMENT,
PRIMARY KEY (id)
) ENGINE=MyISAM AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;

/*!40000 ALTER TABLE customer_number DISABLE KEYS */;

LOCK TABLES address WRITE;

INSERT INTO customer.address VALUES
(37,'512 Main Street','Rexburg', 'Idaho', '83440', 6),
(38, '30 W 2nd S','Rexburg', 'Idaho', '83440', 7);

UNLOCK TABLES;

/*!40000 ALTER TABLE customer_number ENABLE KEYS */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;

DROP TABLE IF EXISTS customer.customer_number;

CREATE TABLE  customer.customer_number (
customer_id int(11) NOT NULL,
phone_id int(11) NOT NULL,
id int(11) NOT NULL AUTO_INCREMENT,
PRIMARY KEY (id)
) ENGINE=MyISAM AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;

/*!40000 ALTER TABLE customer_number DISABLE KEYS */;

LOCK TABLES customer_number WRITE;

INSERT INTO customer.customer_number VALUES
(37,1,1),
(38,3,7),

UNLOCK TABLES;
